.\"
.\"  File: sadoor.key.5
.\"  Author: Claes M. Nyberg <md0claes@mdstud.chalmers.se>
.\"  Description: sadoor.key manual
.\"  Version: 1.0
.\"  Date: Mon Mar 17 20:11:03 CET 2003
.\"
.\"  Copyright (c) 2003 Claes M. Nyberg <md0claes@mdstud.chalmers.se>
.\"  All rights reserved, all wrongs reversed.
.\"     
.\"  Redistribution and use in source and binary forms, with or without
.\"  modification, are permitted provided that the following conditions
.\"  are met:
.\"
.\"  1. Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"  2. Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\"  3. The name of author may not be used to endorse or promote products
.\"     derived from this software without specific prior written permission.
.\"   
.\"  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\"  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
.\"  AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
.\"  THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\"  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\"  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
.\"  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\"  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\"  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\"  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"   
.TH SADOOR.KEY 5 "July 2003" "sadoor daemon version 1.0" " "
.SH NAME
.B sadoor.key
\- sadoor(8) private key file.
.SH DESCRIPTION
The 
.B
sadoor.key
file contains the 448 bit Blowfish key used by the client for 
symmetric encryption of the data/command sent in any command packet. 
Sadoor will refuse to run if the key is not 448 bits.
.PP
The default location is /etc/sadoor/sadoor.key,
but it can be changed in sadoor.conf(5).
.PP
To generate a new key file you are advised to use any of the random
devices (preferable /dev/srandom on OpenBSD and /dev/random on Linux),
like: 
.RS 0
dd if=/dev/srandom of=/etc/sadoor/sadoor.key bs=56 count=1
.PP
If you don't have any random device (Solaris), I guess that you have
to come up with something "random" from the top of your head. 
.RE

.SH AUTHOR
Claes M. Nyberg
.RS 0
.IR <cmn@darklab.org> " or " <md0claes@mdstud.chalmers.se>
.RE
.SH SEE ALSO
dd(1), sadoor.pkts(5), sadoor.conf(5), sadoor(8), mksadb(8)
